/**
 * Dream — deterministic consolidation over a window of daily logs.
 *
 * Walks `<workspace>/memory/YYYY-MM-DD*.md` files within the last N days
 * and produces a structured report:
 *   - which files were considered
 *   - total bytes / lines
 *   - extracted H2/H3 headers across the window (the most common become
 *     "themes")
 *   - first 80 chars of each non-empty header section (key extracts)
 *
 * No LLM. Deterministic — same inputs always produce the same report. The
 * agent reading the persona_dream output is the one who narrates / refines
 * what the consolidation actually means.
 *
 * Side effects on disk (when not dryRun):
 *   1. Append a one-paragraph summary block to `<workspace>/DREAMS.md`.
 *   2. Write the full structured report to
 *      `<workspace>/memory/.dreams/<ISO>.md`.
 */

import { promises as fs } from "node:fs";
import { join } from "node:path";
import { atomicAppendFile, atomicWriteFile } from "./fs-write.js";

export type DreamInput = {
  workspace: string;
  /** Days back to include. Default 7. Hard min 1, max 365. */
  windowDays?: number;
  /** Inject a clock for tests. */
  now?: Date;
  /** Skip the writes — just compute and return the report. */
  dryRun?: boolean;
};

export type DreamFileSummary = {
  /** Workspace-relative path. */
  relPath: string;
  bytes: number;
  lines: number;
  /** YYYY-MM-DD derived from filename. */
  date: string;
};

export type DreamReport = {
  workspace: string;
  windowDays: number;
  rangeStart: string;
  rangeEnd: string;
  /** Files included. */
  files: DreamFileSummary[];
  totalBytes: number;
  totalLines: number;
  /** Top recurring header strings across the window (top 10). */
  themes: Array<{ header: string; count: number }>;
  /** First ~80 chars of each unique section, up to 20 extracts. */
  extracts: string[];
  /** Path written under memory/.dreams/ — undefined for dryRun. */
  detailRelPath?: string;
  /** Bytes appended to DREAMS.md — undefined for dryRun. */
  dreamsMdAppendedBytes?: number;
  dryRun: boolean;
};

const DAILY_LOG_RE = /^(\d{4}-\d{2}-\d{2})/;
const HEADER_RE = /^(##|###)\s+(.+?)\s*$/;

async function listDailyLogs(workspace: string): Promise<string[]> {
  try {
    const entries = await fs.readdir(join(workspace, "memory"));
    return entries.filter((n) => DAILY_LOG_RE.test(n)).sort();
  } catch {
    return [];
  }
}

function clampWindow(d: number | undefined): number {
  if (!d || !Number.isFinite(d)) return 7;
  return Math.max(1, Math.min(Math.floor(d), 365));
}

function isoDate(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

function renderDetail(report: DreamReport): string {
  const lines: string[] = [];
  lines.push(`# Dream — ${report.rangeStart} → ${report.rangeEnd}`);
  lines.push("");
  lines.push(`Window: ${report.windowDays} day(s)`);
  lines.push(`Files: ${report.files.length}`);
  lines.push(`Total bytes: ${report.totalBytes}`);
  lines.push(`Total lines: ${report.totalLines}`);
  lines.push("");
  lines.push("## Files");
  lines.push("");
  for (const f of report.files) {
    lines.push(`- ${f.relPath} (${f.bytes} B, ${f.lines} lines)`);
  }
  lines.push("");
  if (report.themes.length > 0) {
    lines.push("## Recurring themes");
    lines.push("");
    for (const t of report.themes) {
      lines.push(`- ${t.count}× "${t.header}"`);
    }
    lines.push("");
  }
  if (report.extracts.length > 0) {
    lines.push("## Key extracts");
    lines.push("");
    for (const e of report.extracts) lines.push(`> ${e}`);
    lines.push("");
  }
  lines.push("---");
  lines.push("");
  lines.push(
    `_Generated by persona_dream over the ${report.windowDays}-day window ending ${report.rangeEnd}. Deterministic — no LLM. Edit DREAMS.md to add narrative interpretation._`
  );
  return lines.join("\n");
}

function renderDreamsMdEntry(report: DreamReport): string {
  const lines: string[] = [];
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push(`## Dream — ${report.rangeStart} → ${report.rangeEnd}`);
  lines.push("");
  lines.push(
    `${report.files.length} daily log(s) over ${report.windowDays} day(s) · ` +
      `${report.totalBytes} B · ${report.themes.length} recurring theme(s).`
  );
  if (report.themes.length > 0) {
    const top = report.themes.slice(0, 3).map((t) => `"${t.header}" ×${t.count}`).join(", ");
    lines.push("");
    lines.push(`Top themes: ${top}`);
  }
  if (report.detailRelPath) {
    lines.push("");
    lines.push(`Full report: \`${report.detailRelPath}\``);
  }
  lines.push("");
  return lines.join("\n");
}

export async function dream(input: DreamInput): Promise<DreamReport> {
  const now = input.now ?? new Date();
  const windowDays = clampWindow(input.windowDays);
  const rangeEnd = isoDate(now);
  const rangeStartMs = now.getTime() - (windowDays - 1) * 24 * 60 * 60 * 1000;
  const rangeStart = isoDate(new Date(rangeStartMs));
  const dryRun = !!input.dryRun;

  const allLogs = await listDailyLogs(input.workspace);

  // Filter to date window.
  const inWindow = allLogs.filter((name) => {
    const m = DAILY_LOG_RE.exec(name);
    if (!m) return false;
    return m[1] >= rangeStart && m[1] <= rangeEnd;
  });

  const files: DreamFileSummary[] = [];
  const headerCounts = new Map<string, number>();
  const extracts: string[] = [];

  for (const name of inWindow) {
    const rel = `memory/${name}`;
    let text: string;
    try {
      text = await fs.readFile(join(input.workspace, rel), "utf8");
    } catch {
      continue;
    }
    const lns = text.split(/\r?\n/);
    files.push({
      relPath: rel,
      bytes: Buffer.byteLength(text, "utf8"),
      lines: lns.length,
      date: DAILY_LOG_RE.exec(name)![1],
    });

    for (let i = 0; i < lns.length; i++) {
      const hm = HEADER_RE.exec(lns[i]);
      if (!hm) continue;
      const h = hm[2].trim();
      // Normalize timestamps + tag prefixes so "## 2026-05-19T... [#eod]" doesn't
      // dominate the theme list with one-off variants.
      const normalized = h
        .replace(/^\d{4}-\d{2}-\d{2}T[\d:.Z+-]+/, "<timestamp>")
        .replace(/\s*\[#[^\]]+\]\s*/g, "")
        .trim();
      headerCounts.set(normalized, (headerCounts.get(normalized) ?? 0) + 1);

      // Extract: next non-blank line under this header (up to 80 chars).
      for (let j = i + 1; j < Math.min(i + 6, lns.length); j++) {
        const t = lns[j].trim();
        if (!t) continue;
        if (HEADER_RE.test(t)) break;
        if (extracts.length < 20 && t.length > 4) {
          extracts.push(t.slice(0, 80) + (t.length > 80 ? "…" : ""));
        }
        break;
      }
    }
  }

  const themes = [...headerCounts.entries()]
    .filter(([, c]) => c >= 2)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 10)
    .map(([header, count]) => ({ header, count }));

  const report: DreamReport = {
    workspace: input.workspace,
    windowDays,
    rangeStart,
    rangeEnd,
    files,
    totalBytes: files.reduce((s, f) => s + f.bytes, 0),
    totalLines: files.reduce((s, f) => s + f.lines, 0),
    themes,
    extracts,
    dryRun,
  };

  if (!dryRun) {
    const stamp = now.toISOString().replace(/[:.]/g, "-");
    const detailRel = join("memory", ".dreams", `${stamp}.md`);
    const detailAbs = join(input.workspace, detailRel);
    report.detailRelPath = detailRel;

    await atomicWriteFile(detailAbs, renderDetail(report));

    const dreamsEntry = renderDreamsMdEntry(report);
    const dreamsPath = join(input.workspace, "DREAMS.md");
    const { bytes } = await atomicAppendFile(dreamsPath, dreamsEntry);
    report.dreamsMdAppendedBytes = bytes;
  }

  return report;
}

export function renderDreamSummary(r: DreamReport): string {
  const emoji = r.files.length === 0 ? "🟡" : "🟢";
  const mode = r.dryRun ? " (dry-run)" : "";
  const lines: string[] = [];
  lines.push(`${emoji} persona_dream${mode} — ${r.rangeStart} → ${r.rangeEnd} (${r.windowDays}d)`);
  lines.push(`  files: ${r.files.length}, ${r.totalBytes} B total`);
  if (r.themes.length > 0) {
    lines.push(`  themes: ${r.themes.slice(0, 3).map((t) => `${t.count}× "${t.header}"`).join(", ")}`);
  }
  if (!r.dryRun && r.detailRelPath) {
    lines.push(`  detail: ${r.detailRelPath}`);
    lines.push(`  DREAMS.md updated`);
  }
  if (r.files.length === 0) {
    lines.push("  (no daily logs in the window — try persona_checkpoint first)");
  }
  return lines.join("\n");
}
